export const hardware = [
  {
    id: "H100",
    name: "NVIDIA H100",
    vendor: "NVIDIA",
    memory: 80,
    family: "Hopper",
    use: "Training · HPC",
  },
  {
    id: "H200",
    name: "NVIDIA H200",
    vendor: "NVIDIA",
    memory: 141,
    family: "Hopper",
    use: "Large-scale inference",
  },
  {
    id: "B100",
    name: "NVIDIA B100",
    vendor: "NVIDIA",
    memory: 192,
    family: "Blackwell",
    use: "Frontier AI",
  },
  {
    id: "B200",
    name: "NVIDIA B200",
    vendor: "NVIDIA",
    memory: 180,
    family: "Blackwell",
    use: "Frontier AI",
  },
  {
    id: "A100",
    name: "NVIDIA A100",
    vendor: "NVIDIA",
    memory: 80,
    family: "Ampere",
    use: "Training · Research",
  },
  {
    id: "L40S",
    name: "NVIDIA L40S",
    vendor: "NVIDIA",
    memory: 48,
    family: "Ada Lovelace",
    use: "Inference · Rendering",
  },
  {
    id: "L4",
    name: "NVIDIA L4",
    vendor: "NVIDIA",
    memory: 24,
    family: "Ada Lovelace",
    use: "Efficient inference",
  },
  {
    id: "RTX4090",
    name: "NVIDIA RTX 4090",
    vendor: "NVIDIA",
    memory: 24,
    family: "Ada Lovelace",
    use: "Rendering · Fine-tuning",
  },
  {
    id: "RTX5090",
    name: "NVIDIA RTX 5090",
    vendor: "NVIDIA",
    memory: 32,
    family: "Blackwell",
    use: "Rendering · Inference",
  },
  {
    id: "MI300X",
    name: "AMD MI300X",
    vendor: "AMD",
    memory: 192,
    family: "CDNA 3",
    use: "Memory-intensive AI",
  },
  {
    id: "MI325X",
    name: "AMD MI325X",
    vendor: "AMD",
    memory: 256,
    family: "CDNA 3",
    use: "Large model inference",
  },
  {
    id: "CPU-HPC",
    name: "CPU HPC",
    vendor: "MULTI",
    memory: 0,
    family: "CPU",
    use: "Simulation · Quant",
  },
];
export function hardwareId(name: string) {
  const compact = name.toUpperCase().replace(/[ _-]/g, "");
  return (
    hardware.find((h) => compact.includes(h.id.replace("-", "")))?.id ?? name
  );
}
export const templates = [
  {
    id: "inference",
    name: "LLM inference",
    description: "Serve a model with vLLM’s OpenAI-compatible API.",
    image: "vllm/vllm-openai:latest",
    command:
      "python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model Qwen/Qwen2.5-7B-Instruct",
    gpu: "L40S",
    tag: "INFERENCE",
  },
  {
    id: "finetune",
    name: "LLM fine-tuning",
    description: "PyTorch environment for Transformers and PEFT.",
    image: "pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime",
    command: "sleep infinity",
    gpu: "H100",
    tag: "TRAINING",
  },
  {
    id: "diffusion",
    name: "Image generation",
    description: "CUDA-ready PyTorch environment for diffusion pipelines.",
    image: "pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime",
    command: "sleep infinity",
    gpu: "RTX4090",
    tag: "GENERATIVE",
  },
  {
    id: "jupyter",
    name: "Jupyter supercomputer",
    description: "GPU notebook workspace for research and exploration.",
    image: "quay.io/jupyter/pytorch-notebook:cuda12-latest",
    command: "start-notebook.py",
    gpu: "A100",
    tag: "RESEARCH",
  },
  {
    id: "blender",
    name: "Blender farm",
    description: "Headless Blender. Supply your scene and render command.",
    image: "linuxserver/blender:latest",
    command: "blender --background --help",
    gpu: "RTX4090",
    tag: "RENDER",
  },
  {
    id: "custom",
    name: "Custom container",
    description: "Bring your own image, command and environment.",
    image: "nvidia/cuda:12.6.3-runtime-ubuntu24.04",
    command: "sleep infinity",
    gpu: "H100",
    tag: "CUSTOM",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    description: "GPU-enabled TensorFlow training environment.",
    image: "tensorflow/tensorflow:latest-gpu",
    command: "sleep infinity",
    gpu: "A100",
    tag: "TRAINING",
  },
  {
    id: "quant",
    name: "Quant research",
    description: "Scientific Python notebooks for analysis and backtesting.",
    image: "quay.io/jupyter/scipy-notebook:latest",
    command: "start-notebook.py",
    gpu: "CPU-HPC",
    tag: "SCIENTIFIC",
  },
  { id: "quantum", name: "Quantum simulation", description: "CUDA Python environment for Qiskit Aer GPU experiments. Install the quantum SDK and transfer your circuit using the Quantum Lab guide.", image: "pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime", command: "sleep infinity", gpu: "A100", tag: "QUANTUM SIMULATION" },
];
