export type Offer = {
  id: string;
  provider: string;
  providerOfferId: string;
  hardware: string;
  gpuName: string;
  gpuCount: number;
  vram: number | null;
  cpu: number | null;
  ram: number | null;
  disk: number | null;
  region: string;
  price: number;
  currency: "USD";
  availability: "available" | "unknown" | "unavailable";
  availableNodes: number | null;
  reliability: number | null;
  verified: boolean | null;
  bandwidth: number | null;
  benchmark: number | null;
  deployable: boolean;
  observedAt: string;
  billingUnit: "node-hour";
  minimumHours: number | null;
  source: string;
  metadata?: Record<string, unknown>;
};
export type ProviderStatus = {
  id: string;
  name: string;
  status: "connected" | "credentials_required" | "error" | "research";
  detail: string;
  docs: string;
  capabilities: string[];
  offers: number;
};
export type Market = {
  change24h?: number | null;
  hardware: string;
  min: number | null;
  median: number | null;
  average: number | null;
  offers: number;
  gpus: number | null;
  nodes: number | null;
  providers: number;
  regions: string[];
  dispersion: number | null;
};
export type Search = {
  hardware?: string;
  quantity: number;
  durationHours: number;
  region?: string;
  minVram?: number;
  minRam?: number;
  minCpu?: number;
  disk?: number;
  budget?: number;
  strategy: string;
  workload?: string;
};
export type Quote = {
  id: string;
  owner: string;
  offer: Offer;
  durationHours: number;
  hourly: number;
  total: number;
  expiresAt: string;
  createdAt: string;
  status: string;
};
export type Job = {
  credentialId?: string;
  id: string;
  owner: string;
  quoteId: string;
  provider: string;
  providerJobId: string | null;
  hardware: string;
  gpuCount: number;
  region: string;
  hourly: number;
  reserved: number;
  durationHours: number;
  state: string;
  createdAt: string;
  startedAt: string | null;
  endedAt: string | null;
  workloadHash: string;
  image: string;
  error?: string;
  transactionHash?: string;
  receiptHash?: string;
};
