"use client";
import {useEffect,useState} from "react";
import {createPublicClient,http,formatEther,parseEther,type Address,type Abi} from "viem";
import {chain} from "@/lib/chain";
import {curveFactoryAbi,curveProtocol} from "@/lib/curve-launch";
import {tokenAbi} from "@/lib/launch-finance";
import {launchV4,launchPool,launchPoolId,verifyLaunchV4,v4QuoterAbi,v4RouterAbi,permit2Abi,v4SwapArguments,hookReadAbi,type LaunchPool} from "@/lib/launch-v4";
import {useApp} from "./shell";
const rpc=createPublicClient({chain,transport:http(undefined,{timeout:15000,retryCount:1})});
type Send=(address:Address,abi:Abi,name:string,args?:unknown[],value?:bigint)=>Promise<void>;
export function LaunchV4Market({token,symbol,send,busy}:{token:Address;symbol:string;send:Send;busy:boolean}){
 const {owner,connect}=useApp();const [buy,setBuy]=useState(true),[amount,setAmount]=useState(""),[slippage,setSlippage]=useState(100),[error,setError]=useState(""),[working,setWorking]=useState(false),[pendingFees,setPendingFees]=useState("");
 const [quote,setQuote]=useState<{pool:LaunchPool;input:bigint;out:bigint;min:bigint;at:number;owner:string;buy:boolean;slippage:number;tokenAllowance:bigint;routerAllowance:bigint;expiration:number}|null>(null);
 const [review,setReview]=useState<{text:string;run:()=>Promise<void>}|null>(null);
 useEffect(()=>{setQuote(null);setReview(null);},[owner,buy,amount,slippage,token]);
 async function getQuote(){setWorking(true);setError("");setQuote(null);try{if(!owner)throw new Error("Connect your wallet first.");if(!/^(0|[1-9]\d*)(\.\d{1,18})?$/.test(amount))throw new Error("Enter an amount with at most 18 decimals.");const input=parseEther(amount);if(input<=0n||input>=2n**128n)throw new Error("Invalid trade amount.");await verifyLaunchV4(rpc);const launch=await rpc.readContract({address:curveProtocol.factory,abi:curveFactoryAbi,functionName:"getLaunchedToken",args:[token]});if(!launch.exists||launch.phase!==2)throw new Error("Pool is not available for trading.");const pool=launchPool(token,launch.poolFee,launch.tickSpacing);const result=await rpc.simulateContract({address:launchV4.quoter,abi:v4QuoterAbi,functionName:"quoteExactInputSingle",args:[{poolKey:pool,zeroForOne:buy,exactAmount:input,hookData:"0x"}],account:owner as Address});
 const [tokenAllowance,permit]=buy?[0n,[0n,0,0]] as const:await Promise.all([rpc.readContract({address:token,abi:tokenAbi,functionName:"allowance",args:[owner as Address,launchV4.permit2]}),rpc.readContract({address:launchV4.permit2,abi:permit2Abi,functionName:"allowance",args:[owner as Address,token,launchV4.router]})]);const out=result.result[0],min=out*BigInt(10000-slippage)/10000n;if(min<=0n)throw new Error("Amount too small for a protected swap.");setQuote({pool,input,out,min,at:Date.now(),owner,buy,slippage,tokenAllowance,routerAllowance:permit[0],expiration:permit[1]});
 const id=launchPoolId(pool);const fees=await Promise.all([rpc.readContract({address:launchV4.hook,abi:hookReadAbi,functionName:"pendingFees",args:[id,pool.currency0]}),rpc.readContract({address:launchV4.hook,abi:hookReadAbi,functionName:"pendingCreatorTax",args:[id,pool.currency0]}),rpc.readContract({address:launchV4.hook,abi:hookReadAbi,functionName:"pendingFees",args:[id,token]}),rpc.readContract({address:launchV4.hook,abi:hookReadAbi,functionName:"pendingCreatorTax",args:[id,token]})]);setPendingFees(`${formatEther(fees[0]+fees[1])} ETH and ${formatEther(fees[2]+fees[3])} ${symbol} (all recipients combined; operator conversion/distribution may be required).`);
 }catch(e){setError((e as {shortMessage?:string}).shortMessage??(e as Error).message);}finally{setWorking(false);}}
 async function execute(){if(!review)return;setWorking(true);setError("");try{await review.run();setQuote(null);setReview(null);}catch(e){setError((e as {shortMessage?:string}).shortMessage??(e as Error).message);setReview(null);}finally{setWorking(false);}}
 function request(){if(!quote)return;const q=quote;if(!buy&&q.tokenAllowance<q.input){setReview({text:`Approve exactly ${formatEther(q.input)} ${symbol} to Permit2 (${launchV4.permit2}). This is the first of two bounded approval steps.`,run:()=>send(token,tokenAbi,"approve",[launchV4.permit2,q.input])});return;}if(!buy&&(q.routerAllowance<q.input||q.expiration<Date.now()/1000+120)){setReview({text:`Allow the verified swap router to spend exactly ${formatEther(q.input)} ${symbol} through Permit2 for 10 minutes.`,run:()=>send(launchV4.permit2,permit2Abi,"approve",[token,launchV4.router,q.input,Math.floor(Date.now()/1000)+600])});return;}
 setReview({text:`Swap ${formatEther(q.input)} ${buy?"ETH":symbol}. Minimum received ${formatEther(q.min)} ${buy?symbol:"ETH"}, including pool hook fees. Gas is additional.`,run:async()=>{if(q.owner!==owner||q.buy!==buy||q.slippage!==slippage||q.input!==parseEther(amount)||Date.now()-q.at>60000)throw new Error("Quote expired or changed. Get a fresh quote.");await verifyLaunchV4(rpc);await send(launchV4.router,v4RouterAbi,"execute",[...v4SwapArguments(q.pool,buy,q.input,q.min,BigInt(Math.floor(Date.now()/1000)+600))],buy?q.input:0n);}});
 }
 return <section className="curve-trade" aria-label="Graduated pool trading"><h3>Trade the graduated pool</h3><p>Uniswap v4 · permanently locked protocol liquidity · native ETH pair. Quotes include the pool’s hook fees.</p><div className="launch-fields"><label>Direction<select value={buy?"buy":"sell"} onChange={e=>setBuy(e.target.value==="buy")}><option value="buy">Buy {symbol}</option><option value="sell">Sell {symbol}</option></select></label><label>{buy?"ETH to spend":"Tokens to sell"}<input value={amount} inputMode="decimal" onChange={e=>setAmount(e.target.value)}/></label><label>Slippage<select value={slippage} onChange={e=>setSlippage(Number(e.target.value))}><option value={50}>0.5%</option><option value={100}>1%</option><option value={200}>2%</option></select></label></div>{!owner&&<button className="button secondary" onClick={()=>void connect()}>Connect wallet</button>}<button className="button secondary" disabled={busy||working||!owner} onClick={()=>void getQuote()}>Quote pool trade</button>{quote&&<div className="launch-stack-note"><strong>Expected {formatEther(quote.out)} {buy?symbol:"ETH"}</strong><p>Minimum {formatEther(quote.min)} · quote expires after 60 seconds.</p><button className="button primary" disabled={busy||working} onClick={request}>{!buy&&quote.tokenAllowance<quote.input?"Review token approval":!buy&&(quote.routerAllowance<quote.input||quote.expiration<Date.now()/1000+120)?"Review router permission":"Review pool swap"}</button></div>}{review&&<div className="curve-review"><h3>Review transaction</h3><p>{review.text}</p><div className="quantum-actions"><button className="button primary" disabled={busy||working} onClick={()=>void execute()}>{working?"Waiting for wallet / confirmations…":"Confirm in wallet"}</button><button className="button secondary" disabled={busy||working} onClick={()=>setReview(null)}>Cancel</button></div></div>}{pendingFees&&<p>Pending pool fees: {pendingFees}</p>}{error&&<p className="quantum-error" role="alert">{error}</p>}</section>;
}
