"use client";
import { useEffect,useState } from "react";
import { createPublicClient,http,keccak256,formatEther,parseEther,zeroAddress,type Abi,type Address } from "viem";
import { transactionWallet } from "@/lib/wallet-session";
import { useLiveRefresh } from "./use-live-refresh";
import { Coins,ArrowLeftRight,LockKeyhole,Network,ExternalLink } from "lucide-react";
import { chain } from "@/lib/chain";
import { saleAbi,saleTermsSchema,saleDeploymentData,tokenAbi,uniswap,routerAbi,factoryAbi,pairAbi,type SaleTerms } from "@/lib/launch-finance";
import type { LaunchRecord } from "@/lib/launchpad";
import { api,useApp } from "./shell";

const rpc=createPublicClient({chain,transport:http(undefined,{timeout:15000,retryCount:1})});
const units=(value:bigint)=>formatEther(value);
const amount=(value:string)=>{if(!/^(0|[1-9]\d*)(\.\d{1,18})?$/.test(value))throw new Error("Enter a positive amount with at most 18 decimals.");const n=parseEther(value);if(n<=0n)throw new Error("Amount must be positive.");return n;};
const dateInput=(seconds:number)=>{const d=new Date(seconds*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const minOut=(n:bigint,bps:number)=>n*BigInt(10000-bps)/10000n;
type SaleState={funded:boolean;finalized:boolean;successful:boolean;proceedsClaimed:boolean;raised:bigint;contribution:bigint;allowance:bigint;balance:bigint;escrow:bigint;now:number};
type PoolState={weth:Address;pair:Address;tokens:bigint;eth:bigint;shares:bigint;total:bigint;allowance:bigint;lpAllowance:bigint};

export function LaunchNetwork(){return <section className="launch-network" aria-label="Launch destination"><Network size={22}/><div><strong>Launchpad: QuantumPad</strong><span>Network: {chain.name} · Chain ID {chain.id} · Gas: ETH</span></div><p>Your ERC-20 deploys directly from your wallet. This does not list it on Robinhood’s brokerage app.</p><a href={chain.blockExplorers.default.url} target="_blank" rel="noreferrer">Explorer <ExternalLink size={13}/></a></section>;}
export function FinanceOverview(){return <section className="finance-overview" aria-label="Token launch lifecycle"><article><Coins size={22}/><h3>Token & sale</h3><p>Deploy your token, then configure a fixed-price ETH sale with a funding target and closing date.</p></article><article><LockKeyhole size={22}/><h3>Sale escrow</h3><p>Funds stay in the sale contract. Successful sale: token claims and creator proceeds. Failed sale: buyer refunds.</p></article><article><ArrowLeftRight size={22}/><h3>Liquidity & trading</h3><p>Approve, add or remove token/ETH liquidity and swap through Uniswap v2 on Robinhood Chain from the project page.</p></article></section>;}

export function LaunchFinance({record,onChange}:{record:LaunchRecord;onChange:(r:LaunchRecord)=>void}){
  const {owner,walletProvider,connect}=useApp();const own=owner===record.owner;
  const token=record.deployment?.address,sale=record.sale;
  const [tab,setTab]=useState("sale"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[tx,setTx]=useState("");
  const [review,setReview]=useState<{label:string;description:string;run:()=>Promise<void>}|null>(null);
  const [terms,setTerms]=useState<SaleTerms>({tokensPerEth:"1000",softCap:"1",hardCap:"10",start:Math.floor(Date.now()/1000)+86400,end:Math.floor(Date.now()/1000)+604800});
  const [saleHash,setSaleHash]=useState(""),[attempted,setAttempted]=useState(false),[buy,setBuy]=useState("");
  const [state,setState]=useState<SaleState|null>(null),[pool,setPool]=useState<PoolState|null>(null),[readError,setReadError]=useState(""),[poolError,setPoolError]=useState("");
  const [tokenAmount,setTokenAmount]=useState(""),[ethAmount,setEthAmount]=useState(""),[lpAmount,setLpAmount]=useState(""),[swapAmount,setSwapAmount]=useState(""),[direction,setDirection]=useState("buy"),[slippage,setSlippage]=useState(100);
  const [quote,setQuote]=useState<{input:string;direction:string;out:bigint;at:number}|null>(null);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(`exaflop:sale:${record.id}`)??"null");if(saved){setTerms(saleTermsSchema.parse(saved.terms));setSaleHash(saved.hash??"");setAttempted(true);}}catch{}},[record.id]);
  const read=(address:Address,abi:Abi,functionName:string,args:unknown[]=[])=>rpc.readContract({address,abi,functionName,args});
  async function refresh(){
    if(!token||record.manifest.chainId!==chain.id)return;setReadError("");setPoolError("");
    try{
      if(await rpc.getChainId()!==chain.id)throw new Error("RPC network mismatch.");
      if(sale){
        const fields=await Promise.all(["funded","finalized","successful","proceedsClaimed","raised"].map(name=>read(sale.address,saleAbi,name)));
        const [contribution,allowance,balance,escrow,block]=await Promise.all([read(sale.address,saleAbi,"contributions",[owner||zeroAddress]),read(token,tokenAbi,"allowance",[owner||zeroAddress,sale.address]),read(token,tokenAbi,"balanceOf",[owner||zeroAddress]),rpc.getBalance({address:sale.address}),rpc.getBlock()]);
        setState({funded:fields[0] as boolean,finalized:fields[1] as boolean,successful:fields[2] as boolean,proceedsClaimed:fields[3] as boolean,raised:fields[4] as bigint,contribution:contribution as bigint,allowance:allowance as bigint,balance:balance as bigint,escrow,now:Number(block.timestamp)});
      }
      if(chain.id!==uniswap.chainId){setPool(null);return;}
      try { const [factory,weth,code]=await Promise.all([read(uniswap.router,routerAbi,"factory"),read(uniswap.router,routerAbi,"WETH"),rpc.getCode({address:uniswap.router})]);
      if(!code||code==="0x"||String(factory).toLowerCase()!==uniswap.factory||String(weth).toLowerCase()!==uniswap.weth||keccak256(code)!==uniswap.routerCodeHash)throw new Error("Uniswap deployment verification failed.");
      const pair=await read(uniswap.factory,factoryAbi,"getPair",[token,weth]) as Address;
      const allowance=await read(token,tokenAbi,"allowance",[owner||zeroAddress,uniswap.router]) as bigint;
      let tokens=0n,eth=0n,shares=0n,total=0n,lpAllowance=0n;
      if(pair!==zeroAddress){const [first,reserves,owned,supply,approved]=await Promise.all([read(pair,pairAbi,"token0"),read(pair,pairAbi,"getReserves"),read(pair,tokenAbi,"balanceOf",[owner||zeroAddress]),read(pair,tokenAbi,"totalSupply"),read(pair,tokenAbi,"allowance",[owner||zeroAddress,uniswap.router])]);const [r0,r1]=reserves as [bigint,bigint,number];const tokenFirst=String(first).toLowerCase()===token.toLowerCase();tokens=tokenFirst?r0:r1;eth=tokenFirst?r1:r0;shares=owned as bigint;total=supply as bigint;lpAllowance=approved as bigint;}
      setPool({weth:weth as Address,pair,tokens,eth,shares,total,allowance,lpAllowance});
      }catch(e){setPoolError((e as Error).message);setPool(null);}
    }catch(e){setReadError((e as Error).message);setPool(null);}
  }
  useEffect(()=>{void refresh();},[token,sale?.address,owner]); // refresh after each transaction and on demand
  useLiveRefresh(async()=>{if(!busy)await refresh();});
  useEffect(()=>{setReview(null);setQuote(null);},[owner,token]);
  const wallet=()=>transactionWallet(owner,walletProvider,connect);
  async function send(address:Address,abi:Abi,functionName:string,args:unknown[]=[],value=0n){const w=await wallet();const {request}=await rpc.simulateContract({address,abi,functionName,args,account:w.address,value});const gas=await rpc.estimateContractGas({address,abi,functionName,args,account:w.address,value});const hash=await w.client.writeContract({...request,gas:gas*120n/100n+80000n} as any);setTx(hash);await rpc.waitForTransactionReceipt({hash,confirmations:1,timeout:120000}).then(r=>{if(r.status!=="success")throw new Error("Transaction reverted.");});await refresh();}
  async function execute(){if(!review)return;setBusy(true);setError("");try{await review.run();setReview(null);}catch(e){setError((e as {shortMessage?:string}).shortMessage??(e as Error).message);}finally{setBusy(false);}}
  function ask(label:string,description:string,run:()=>Promise<void>){setError("");if(!owner){void connect();return;}setReview({label,description,run});}
  function checked(action:()=>void){try{action();}catch(e){setError((e as Error).message);}}
  async function deploySale(){
    const parsed=saleTermsSchema.parse(terms);if(parsed.start<Date.now()/1000+300)throw new Error("Choose a start at least five minutes ahead so you can fund the sale.");
    if(parseEther(parsed.hardCap)*BigInt(parsed.tokensPerEth)>parseEther(record.manifest.project.supply))throw new Error("Sale inventory exceeds total token supply.");
    const w=await wallet();if(w.address.toLowerCase()!==record.owner)throw new Error("Creator wallet required.");
    const data=saleDeploymentData(record,parsed),gas=await rpc.estimateGas({account:w.address,data});
    localStorage.setItem(`exaflop:sale:${record.id}`,JSON.stringify({terms:parsed,hash:""}));setAttempted(true);
    try{const hash=await w.client.sendTransaction({account:w.address,data,gas:gas*120n/100n});setSaleHash(hash);setTx(hash);localStorage.setItem(`exaflop:sale:${record.id}`,JSON.stringify({terms:parsed,hash}));
      const receipt=await rpc.waitForTransactionReceipt({hash,confirmations:3,timeout:120000});
      if(receipt.status!=="success"){localStorage.removeItem(`exaflop:sale:${record.id}`);setAttempted(false);setSaleHash("");throw new Error("Sale deployment reverted. Review the error before trying again.");}
      setSaleHash(receipt.transactionHash);setTx(receipt.transactionHash);localStorage.setItem(`exaflop:sale:${record.id}`,JSON.stringify({terms:parsed,hash:receipt.transactionHash}));
      const result=await api<{launch:LaunchRecord}>("launchpad",{action:"register-sale",id:record.id,transaction:receipt.transactionHash,terms:parsed});onChange(result.launch);
    }
    catch(e){let cause:unknown=e;for(let i=0;i<8&&cause&&typeof cause==="object";i++){const c=cause as {code?:number;cause?:unknown};if(c.code===4001){setAttempted(false);localStorage.removeItem(`exaflop:sale:${record.id}`);break;}cause=c.cause;}throw e;}
  }
  async function registerSale(){const data=await api<{launch:LaunchRecord}>("launchpad",{action:"register-sale",id:record.id,transaction:saleHash,terms});onChange(data.launch);}
  async function quoteSwap(){setBusy(true);setError("");try{if(!pool||!token||!pool.eth||!pool.tokens)throw new Error("Fund a token/ETH pool first.");const path=direction==="buy"?[pool.weth,token]:[token,pool.weth];const outputs=await rpc.readContract({address:uniswap.router,abi:routerAbi,functionName:"getAmountsOut",args:[amount(swapAmount),path]});setQuote({input:swapAmount,direction,out:outputs[1],at:Date.now()});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(record.manifest.chainId!==chain.id)return <p className="quantum-error">This launch belongs to chain {record.manifest.chainId}. Financial actions are unavailable on the configured network.</p>;
  const saleStatus=state?.finalized?(state.successful?"Successful · claims open":"Failed / cancelled · refunds open"):state?.funded?(state.now<sale!.terms.start?"Funded · scheduled":state.now>=sale!.terms.end?"Awaiting finalization":"Open for contributions"):"Awaiting token inventory";
  const inventory=sale?parseEther(sale.terms.hardCap)*BigInt(sale.terms.tokensPerEth):0n;
  return <section className="panel quantum-section launch-finance" aria-label="Sale liquidity and escrow"><div className="quantum-section-heading"><div><span className="eyebrow">LAUNCH OPERATIONS</span><h2>Sale. Liquidity. Escrow.</h2><p>Every transaction is reviewed in your wallet on {chain.name}. Custom sale contracts are not independently audited. No automatic brokerage listing or guaranteed market.</p></div>{token&&<button className="button secondary" disabled={busy} onClick={()=>void refresh()}>Refresh on-chain state</button>}</div>
    <div className="finance-tabs" role="group" aria-label="Launch operations">{[{id:"sale",label:"Token sale",Icon:Coins},{id:"liquidity",label:"Liquidity & swap",Icon:ArrowLeftRight},{id:"escrow",label:"Escrow & claims",Icon:LockKeyhole}].map(({id,label,Icon})=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</div>
    {!token?<div className="launch-stack-note"><h3>Verify the token deployment first.</h3><p>Sale deployment, liquidity provisioning and buyer controls appear here after the creator registers the token contract above.</p></div>:<>
    {readError&&<p className="quantum-error" role="alert">On-chain read unavailable: {readError}. Refresh before transacting.</p>}
    <fieldset disabled={busy||!!review} className="finance-fieldset">
    {tab==="sale"&&!sale&&(own?<><h3>Configure a fixed-price sale</h3><p>Terms become immutable when deployed. Approve and fund the entire hard-cap token allocation before the start time. The sale has no platform fee and has not received an independent security audit.</p><div className="launch-fields">
      <label>Whole tokens per 1 ETH<input disabled={attempted} value={terms.tokensPerEth} onChange={e=>setTerms({...terms,tokensPerEth:e.target.value})}/></label><label>Minimum raise / soft cap (ETH)<input disabled={attempted} value={terms.softCap} onChange={e=>setTerms({...terms,softCap:e.target.value})}/></label><label>Maximum raise / hard cap (ETH)<input disabled={attempted} value={terms.hardCap} onChange={e=>setTerms({...terms,hardCap:e.target.value})}/></label><label>Start (your local time)<input disabled={attempted} type="datetime-local" value={dateInput(terms.start)} onChange={e=>{const n=Date.parse(e.target.value);if(Number.isFinite(n))setTerms({...terms,start:Math.floor(n/1000)});}}/></label><label>End (your local time)<input disabled={attempted} type="datetime-local" value={dateInput(terms.end)} onChange={e=>{const n=Date.parse(e.target.value);if(Number.isFinite(n))setTerms({...terms,end:Math.floor(n/1000)});}}/></label></div>
      <button disabled={attempted} className="button primary" onClick={()=>ask("Deploy sale contract",`Rate: ${terms.tokensPerEth} tokens/ETH. Caps: ${terms.softCap}–${terms.hardCap} ETH. All successful-sale proceeds go to the creator; no milestone restrictions or automatic liquidity allocation.`,deploySale)}>Review sale deployment</button>
      {attempted&&<p>A deployment request was attempted. Recover its transaction hash from your wallet; do not deploy a duplicate. Rejected wallet requests can be retried.</p>}<label>Sale deployment transaction hash<input value={saleHash} onChange={e=>setSaleHash(e.target.value)} placeholder="0x…"/></label><button className="button secondary" disabled={!/^0x[0-9a-fA-F]{64}$/.test(saleHash)} onClick={()=>ask("Register sale","Verify exact contract code, creator and terms after three confirmations. This sends no funds.",registerSale)}>Verify & register sale</button>
    </>:<p>The creator can configure a sale after deploying the token. No sale contract has been registered.</p>)}
    {(tab==="sale"||tab==="escrow")&&sale&&state&&<><div className="finance-readout"><span>{saleStatus}</span><strong>{units(state.raised)} / {sale.terms.hardCap} ETH</strong><small>Minimum raise {sale.terms.softCap} ETH · {sale.terms.tokensPerEth} tokens per ETH</small></div><dl className="launch-facts"><div><dt>Sale contract</dt><dd><a href={`${chain.blockExplorers.default.url}/address/${sale.address}`} target="_blank" rel="noreferrer">{sale.address} ↗</a></dd></div><div><dt>Sale window</dt><dd>{new Date(sale.terms.start*1000).toLocaleString()} → {new Date(sale.terms.end*1000).toLocaleString()}</dd></div><div><dt>Your unclaimed contribution</dt><dd>{units(state.contribution)} ETH</dd></div><div><dt>ETH in contract</dt><dd>{units(state.escrow)} ETH</dd></div></dl>
      {tab==="sale"&&<><label>Contribution (ETH)<input value={buy} onChange={e=>setBuy(e.target.value)} inputMode="decimal"/></label><button disabled={!!readError||!state.funded||state.finalized||state.now<sale.terms.start||state.now>=sale.terms.end} className="button primary" onClick={()=>checked(()=>{const value=amount(buy);if(value+state.raised>parseEther(sale.terms.hardCap))throw new Error("Contribution exceeds remaining hard cap.");ask("Contribute to sale",`Commit ${buy} ETH for ${units(value*BigInt(sale.terms.tokensPerEth))} tokens if the sale succeeds. Refunds are available only if it fails or is cancelled; there is no withdrawal during the sale.`,()=>send(sale.address,saleAbi,"buy",[],value));})}>Review contribution</button></>}
      {own&&!state.funded&&!state.finalized&&<div className="launch-stack-note"><h3>Fund {units(inventory)} tokens before the start</h3><p>Your token balance: {units(state.balance)}. Approval and funding are separate wallet transactions.</p><button className="button secondary" disabled={!!readError||state.now>=sale.terms.start} onClick={()=>ask("Approve sale inventory",`Allow this sale contract to transfer exactly ${units(inventory)} tokens.`,()=>send(token,tokenAbi,"approve",[sale.address,inventory]))}>Approve token inventory</button><button className="button primary" disabled={!!readError||state.allowance<inventory||state.balance<inventory||state.now>=sale.terms.start} onClick={()=>ask("Fund sale inventory",`Transfer ${units(inventory)} tokens into sale escrow.`,()=>send(sale.address,saleAbi,"fund"))}>Fund sale</button></div>}
      <div className="quantum-actions"><button className="button secondary" disabled={!!readError||state.finalized||(state.now<sale.terms.end&&state.raised<parseEther(sale.terms.hardCap))} onClick={()=>ask("Finalize sale","Resolve the outcome from the immutable soft cap. Anyone may finalize after the end or when the hard cap is reached.",()=>send(sale.address,saleAbi,"finalize"))}>Finalize outcome</button>
      <button className="button primary" disabled={!!readError||!state.finalized||!state.successful||state.contribution===0n} onClick={()=>ask("Claim tokens",`Receive ${units(state.contribution*BigInt(sale.terms.tokensPerEth))} tokens in your connected wallet.`,()=>send(sale.address,saleAbi,"claimTokens"))}>Claim tokens</button>
      <button className="button secondary" disabled={!!readError||!state.finalized||state.successful||state.contribution===0n} onClick={()=>ask("Claim refund",`Return your ${units(state.contribution)} ETH contribution to your connected wallet. Network gas is not refunded.`,()=>send(sale.address,saleAbi,"refund"))}>Claim refund</button></div>
      {own&&<div className="quantum-actions"><button className="button secondary" disabled={!!readError||!state.successful||state.proceedsClaimed} onClick={()=>ask("Withdraw sale proceeds",`Transfer ${units(state.raised)} ETH to the creator wallet.`,()=>send(sale.address,saleAbi,"withdrawProceeds"))}>Withdraw proceeds</button><button className="button secondary" disabled={!!readError||!state.finalized} onClick={()=>ask("Recover unsold tokens","Return surplus inventory to the creator. Buyer token claims remain reserved in the contract.",()=>send(sale.address,saleAbi,"recoverUnsoldTokens"))}>Recover unsold tokens</button><button className="button secondary" disabled={!!readError||state.finalized||state.now>=sale.terms.start} onClick={()=>ask("Cancel scheduled sale","Permanently cancel this sale before its start. A cancelled sale cannot be restarted.",()=>send(sale.address,saleAbi,"cancelBeforeStart"))}>Cancel before start</button></div>}
    </>}
    {tab==="escrow"&&<div className="launch-stack-note"><h3>Escrow rules are enforced by the sale contract.</h3><p>Before a successful finalization, the creator cannot withdraw contributions. A failed sale lets each buyer claim their ETH back. A successful sale unlocks creator proceeds and buyer token claims. This does not enforce project delivery, compute spending, milestones or liquidity commitments.</p>{!sale&&<p>No escrow exists for this project until a sale is deployed and funded.</p>}<a href="/downloads/genesis-sale-source.json" download>Download sale contract compiler input ↗</a></div>}
    {tab==="liquidity"&&<><h3>Uniswap v2 · token / ETH</h3><p>Liquidity and swaps use Uniswap contracts directly. LP shares belong to the wallet providing liquidity and are not locked. Pool creation does not guarantee buyers or a stable price.</p><a href="https://developers.uniswap.org/docs/protocols/v2/deployments" target="_blank" rel="noreferrer">Official router registry ↗</a>{chain.id!==uniswap.chainId?<p>No verified Uniswap integration is configured for this test network.</p>:!pool?<p>{poolError||"Waiting for verified router and pool state."} Refresh on-chain state to retry.</p>:<>
      <div className="finance-readout"><span>{pool.pair===zeroAddress?"No pool yet · first deposit sets the price":"Token / wrapped ETH pool"}</span><strong>{units(pool.tokens)} tokens / {units(pool.eth)} ETH</strong><small>Your LP shares: {units(pool.shares)}</small></div>
      <label>Slippage protection<select value={slippage} onChange={e=>setSlippage(Number(e.target.value))}><option value={50}>0.5%</option><option value={100}>1%</option><option value={200}>2%</option></select></label>
      <div className="finance-columns"><section><h3>Add liquidity</h3><div className="launch-fields"><label>Maximum tokens<input value={tokenAmount} onChange={e=>setTokenAmount(e.target.value)} inputMode="decimal"/></label><label>Maximum ETH<input value={ethAmount} onChange={e=>setEthAmount(e.target.value)} inputMode="decimal"/></label></div><p>For an existing pool, deposits follow its reserve ratio; unused amounts stay in or return to your wallet.</p><button className="button secondary" onClick={()=>checked(()=>{const n=amount(tokenAmount);ask("Approve liquidity tokens",`Approve exactly ${tokenAmount} tokens to the official Uniswap router.`,()=>send(token,tokenAbi,"approve",[uniswap.router,n]));})}>Approve tokens</button><button className="button primary" onClick={()=>checked(()=>{const t=amount(tokenAmount),e=amount(ethAmount);if(pool.allowance<t)throw new Error("Approve the token amount first, then refresh.");let usedT=t,usedE=e;if(pool.tokens>0n&&pool.eth>0n){const optimalE=t*pool.eth/pool.tokens;if(optimalE<=e)usedE=optimalE;else usedT=e*pool.tokens/pool.eth;}if(minOut(usedT,slippage)===0n||minOut(usedE,slippage)===0n)throw new Error("Deposit is too small.");ask("Add token/ETH liquidity",`Maximum ${tokenAmount} tokens + ${ethAmount} ETH. Minimum accepted: ${units(minOut(usedT,slippage))} tokens and ${units(minOut(usedE,slippage))} ETH. LP shares go to your wallet and remain withdrawable.`,()=>send(uniswap.router,routerAbi,"addLiquidityETH",[token,t,minOut(usedT,slippage),minOut(usedE,slippage),owner,BigInt(Math.floor(Date.now()/1000)+600)],e));})}>Review liquidity deposit</button></section>
      <section><h3>Remove liquidity</h3><label>LP shares to redeem<input value={lpAmount} onChange={e=>setLpAmount(e.target.value)} inputMode="decimal"/></label><button className="button secondary" disabled={pool.pair===zeroAddress} onClick={()=>checked(()=>{const n=amount(lpAmount);if(n>pool.shares)throw new Error("Insufficient LP shares.");ask("Approve LP redemption",`Approve exactly ${lpAmount} LP shares to the Uniswap router.`,()=>send(pool.pair,tokenAbi,"approve",[uniswap.router,n]));})}>Approve LP shares</button><button className="button secondary" disabled={pool.total===0n} onClick={()=>checked(()=>{const n=amount(lpAmount);if(n>pool.shares||n>pool.lpAllowance)throw new Error("Check your LP balance and approval.");const t=minOut(n*pool.tokens/pool.total,slippage),e=minOut(n*pool.eth/pool.total,slippage);if(t===0n||e===0n)throw new Error("Redemption is too small for slippage protection.");ask("Remove liquidity",`Redeem ${lpAmount} LP shares for at least ${units(t)} tokens and ${units(e)} ETH.`,()=>send(uniswap.router,routerAbi,"removeLiquidityETH",[token,n,t,e,owner,BigInt(Math.floor(Date.now()/1000)+600)]));})}>Review removal</button></section></div>
      <section className="launch-stack-note"><h3>Swap in QuantumPad</h3><div className="launch-fields"><label>Direction<select value={direction} onChange={e=>{setDirection(e.target.value);setQuote(null);}}><option value="buy">ETH → token</option><option value="sell">Token → ETH</option></select></label><label>Amount in {direction==="buy"?"ETH":"tokens"}<input value={swapAmount} onChange={e=>{setSwapAmount(e.target.value);setQuote(null);}} inputMode="decimal"/></label></div><button className="button secondary" onClick={()=>void quoteSwap()}>Get on-chain quote</button>{quote&&<p>Quoted output: {units(quote.out)} {quote.direction==="buy"?"tokens":"ETH"}. Minimum: {units(minOut(quote.out,slippage))}. Quote expires after 60 seconds.</p>}{direction==="sell"&&<button className="button secondary" onClick={()=>checked(()=>{const n=amount(swapAmount);ask("Approve swap tokens",`Approve exactly ${swapAmount} tokens to Uniswap.`,()=>send(token,tokenAbi,"approve",[uniswap.router,n]));})}>Approve swap tokens</button>}<button className="button primary" disabled={!quote} onClick={()=>checked(()=>{if(!quote||quote.input!==swapAmount||quote.direction!==direction||Date.now()-quote.at>60000)throw new Error("Refresh your quote before swapping.");const n=amount(swapAmount),minimum=minOut(quote.out,slippage);if(minimum<=0n)throw new Error("Swap output is too small.");if(direction==="sell"&&pool.allowance<n)throw new Error("Approve tokens first.");ask("Swap through Uniswap",`Spend ${swapAmount} ${direction==="buy"?"ETH":"tokens"}; receive at least ${units(minimum)} ${direction==="buy"?"tokens":"ETH"}.`,async()=>{if(Date.now()-quote.at>60000)throw new Error("Quote expired. Close this review and request a fresh quote.");const deadline=BigInt(Math.floor(Date.now()/1000)+600);await(direction==="buy"?send(uniswap.router,routerAbi,"swapExactETHForTokens",[minimum,[pool.weth,token],owner,deadline],n):send(uniswap.router,routerAbi,"swapExactTokensForETH",[n,minimum,[token,pool.weth],owner,deadline]));setQuote(null);});})}>Review swap</button></section>
      {pool.pair!==zeroAddress&&<a href={`${chain.blockExplorers.default.url}/address/${pool.pair}`} target="_blank" rel="noreferrer">Inspect liquidity pool ↗</a>}
    </>}</>}
    </fieldset></>}
    {review&&<section className="finance-review" aria-label="Transaction review"><h3>{review.label}</h3><p>{review.description}</p><dl className="launch-facts"><div><dt>Network</dt><dd>{chain.name} · {chain.id}</dd></div><div><dt>Connected wallet</dt><dd>{owner||"Connect wallet to proceed"}</dd></div></dl><p>Network gas applies. Review the destination and amounts in your wallet before signing.</p><button className="button primary" disabled={busy} onClick={()=>void execute()}>{busy?"Waiting for wallet / confirmation…":"Continue to wallet"}</button><button className="button secondary" disabled={busy} onClick={()=>setReview(null)}>Cancel review</button></section>}
    {error&&<p className="quantum-error" role="alert">{error} If a transaction was broadcast, check its status before retrying.</p>}{tx&&<p role="status"><a href={`${chain.blockExplorers.default.url}/tx/${tx}`} target="_blank" rel="noreferrer">Latest transaction: {tx} ↗</a></p>}
  </section>;
}
