"use client";
import { useState } from "react";
import Link from "next/link";
import { Atom, ArrowUpRight, Cpu, Download, FlaskConical, Network, Play, Plus, RotateCcw, Upload, X } from "lucide-react";
import { presets, simulate, sample, qasm, hybridSweep, parseResult, type Circuit, type Gate, type QuantumResult } from "@/lib/quantum";

function download(name:string,text:string,type="application/json") {const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const gateNames:Gate["kind"][]=["H","X","Y","Z","S","T","RX","RY","RZ","CX"];
const tabs=[['lab','Circuit lab',FlaskConical],['devices','Devices & access',Atom],['simulation','GPU simulation',Cpu],['hybrid','Hybrid workflows',Network]] as const;
const providers=[
  {name:"IBM Quantum",kind:"Gate-based QPUs",description:"Discover backends accessible to your IBM instance, transpile your circuit, and submit with Sampler V2.",url:"https://quantum.cloud.ibm.com/",docs:"https://quantum.cloud.ibm.com/docs/en/api/qiskit-ibm-runtime/runtime-service",command:"python exaflop-quantum.py devices --provider ibm"},
  {name:"Amazon Braket",kind:"QPUs & simulators",description:"Discover devices through your AWS account. Device availability, queue and supported gates come from AWS.",url:"https://console.aws.amazon.com/braket/",docs:"https://docs.aws.amazon.com/braket/latest/developerguide/what-is-braket.html",command:"python exaflop-quantum.py devices --provider braket"},
];
export function Quantum() {
  const [tab,setTab]=useState("lab"),[circuit,setCircuit]=useState<Circuit>(presets.bell),[gate,setGate]=useState<Gate["kind"]>("H"),[target,setTarget]=useState(0),[control,setControl]=useState(1),[angle,setAngle]=useState(Math.PI/2),[shots,setShots]=useState(1024),[noise,setNoise]=useState(0);
  const [result,setResult]=useState<{circuit:Circuit;probabilities:number[];counts:number[];bloch:ReturnType<typeof simulate>["bloch"];shots:number;noise:number}|null>(null),[error,setError]=useState(""),[imported,setImported]=useState<QuantumResult|null>(null);
  const [hybrid,setHybrid]=useState<ReturnType<typeof hybridSweep>|null>(null),[algorithm,setAlgorithm]=useState<"qaoa"|"vqe">("qaoa"),[memoryQubits,setMemoryQubits]=useState(28);
  const [devices,setDevices]=useState<{name:string;provider:string;qubits:number|null;status:string;queue:string;gates:string}[]>([]),[deviceDate,setDeviceDate]=useState("");
  const edit=(next:Circuit)=>{setCircuit(next);setTarget(t=>Math.min(t,next.qubits-1));setControl(c=>Math.min(c,next.qubits-1));setResult(null);setError("");};
  const request=()=>download("quantum-request.json",JSON.stringify({schema:"exaflop.quantum.request.v1",...circuit,shots},null,2));
  function run(){try{const out=simulate(circuit);setResult({...out,circuit:structuredClone(circuit),counts:sample(out.probabilities,shots,noise),shots,noise});setError("");}catch(e){setError((e as Error).message);}}
  async function importFile(file:File|undefined,kind:"result"|"devices") {if(!file)return;try{if(file.size>200_000)throw new Error("Choose a JSON file smaller than 200 KB.");const data=JSON.parse(await file.text());if(kind==="result"){setImported(parseResult(data));}else{if(data.schema!=="exaflop.quantum.devices.v1"||!Array.isArray(data.devices)||data.devices.length>150||typeof data.observedAt!=="string"||data.observedAt.length>100)throw new Error("Choose the devices.json file exported by the runner.");for(const d of data.devices)if(!d||![d.name,d.provider,d.status,d.queue,d.gates].every(v=>typeof v==="string"&&v.length<5000)||(d.qubits!==null&&(!Number.isInteger(d.qubits)||d.qubits<1)))throw new Error("Invalid device record.");setDevices(data.devices);setDeviceDate(data.observedAt);}setError("");}catch(e){setError((e as Error).message);}}
  const reference=imported?simulate(imported.circuit).probabilities:[];
  const importedShots=imported?Object.values(imported.counts).reduce((a,b)=>a+b,0):0;
  const distance=imported?reference.reduce((s,p,i)=>s+Math.abs(p-(imported.counts[i.toString(2).padStart(imported.qubits,"0")]??0)/importedShots),0)/2:0;
  return <div className="page quantum-page">
    <header className="page-heading"><span className="feature-emblem"><Atom size={32} strokeWidth={1.2}/></span><div><div className="eyebrow">QUANTUM / EXPERIMENT WORKSPACE</div><h1>From a circuit to a discovery.</h1><p>Simulate here. Explore real quantum devices. Take your experiment to your own provider account.</p></div><span className="badge">LOCAL LAB · NO ACCOUNT NEEDED</span></header>
    <div className="quantum-actions"><Link className="button secondary" href="/launchpad">Launch a token with your experiment ↗</Link></div>
    <nav className="quantum-tabs" aria-label="Quantum features">{tabs.map(([id,label,Icon])=><button key={id} aria-current={tab===id?"page":undefined} onClick={()=>{setTab(id);setError("");}}><Icon size={17}/>{label}</button>)}</nav>
    {error&&<p role="alert" className="quantum-error">{error}</p>}
    {tab==="lab"&&<>
      <div className="quantum-grid"><section className="panel quantum-editor"><div className="quantum-section-heading"><div><span className="eyebrow">01 / CIRCUIT STUDIO</span><h2>Build a quantum state.</h2></div><Atom size={23}/></div>
        <div className="quantum-presets">{Object.keys(presets).map(id=><button className="button secondary" key={id} onClick={()=>edit(structuredClone(presets[id]))}>{({bell:"Bell pair",ghz:"GHZ state",interference:"Interference",grover:"Grover search"})[id]}</button>)}</div>
        <div className="quantum-form"><label>Qubits<select value={circuit.qubits} onChange={e=>{edit({qubits:Number(e.target.value),gates:[]});setTarget(0);setControl(Number(e.target.value)>1?1:0);}}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label><label>Shots<select value={shots} onChange={e=>{setShots(+e.target.value);setResult(null);}}>{[128,512,1024,4096,8192].map(n=><option key={n}>{n}</option>)}</select></label><label>Readout flips<select value={noise} onChange={e=>{setNoise(+e.target.value);setResult(null);}}><option value={0}>Ideal</option><option value={.01}>1% per bit</option><option value={.05}>5% per bit</option><option value={.1}>10% per bit</option></select></label></div>
        <div className="quantum-circuit" aria-label="Circuit diagram; q0 is the least significant bit">{Array.from({length:circuit.qubits},(_,q)=><div className="quantum-wire" key={q}><b>q{q} |0⟩</b>{circuit.gates.map((g,i)=><span key={i} className={g.target===q||g.control===q?"quantum-gate":"quantum-pass"} title={`Step ${i+1}: ${g.kind} on q${g.target}${g.kind==="CX"?` controlled by q${g.control}`:""}`}>{g.target===q?g.kind:g.control===q&&g.kind==="CX"?"●":"─"}</span>)}<span>→ M</span></div>)}</div>
        <div className="quantum-form"><label>Gate<select value={gate} onChange={e=>setGate(e.target.value as Gate["kind"])}>{gateNames.map(g=><option key={g}>{g}</option>)}</select></label><label>Target<select value={target} onChange={e=>setTarget(+e.target.value)}>{Array.from({length:circuit.qubits},(_,i)=><option value={i} key={i}>q{i}</option>)}</select></label>{gate==="CX"&&<label>Control<select value={control} onChange={e=>setControl(+e.target.value)}>{Array.from({length:circuit.qubits},(_,i)=><option value={i} key={i}>q{i}</option>)}</select></label>}{gate.startsWith("R")&&<label>Angle (radians)<input type="number" step="0.1" min={-100*Math.PI} max={100*Math.PI} value={angle} onChange={e=>setAngle(+e.target.value)}/></label>}</div>
        <div className="quantum-actions"><button className="button secondary" disabled={circuit.gates.length>=64||(gate==="CX"&&control===target)||!Number.isFinite(angle)} onClick={()=>edit({...circuit,gates:[...circuit.gates,{kind:gate,target,...(gate==="CX"?{control}:{}),...(gate.startsWith("R")?{angle}:{})}]})}><Plus size={15}/>Add gate</button><button className="button secondary" disabled={!circuit.gates.length} onClick={()=>edit({...circuit,gates:circuit.gates.slice(0,-1)})}><RotateCcw size={14}/>Undo</button><button className="button secondary" disabled={!circuit.gates.length} onClick={()=>edit({...circuit,gates:[]})}><X size={14}/>Clear</button></div>
        <p className="muted">{circuit.gates.length}/64 gates · Bitstrings read q{circuit.qubits-1}…q0. Changing qubit count clears the circuit. Readout flips model measurement errors only, not a calibrated QPU.</p>
        <div className="quantum-actions"><button className="button primary" onClick={run}><Play size={16}/>Run simulation</button><button className="button secondary" onClick={()=>download("circuit.qasm",qasm(circuit),"text/plain")}><Download size={15}/>OpenQASM</button><button className="button secondary" onClick={request}>Export request</button></div>
      </section>
      <section className="panel quantum-output" aria-label="Simulation results"><div className="quantum-section-heading"><div><span className="eyebrow">02 / STATE & MEASUREMENT</span><h2>{result?"Your circuit, measured.":"Explore the possibilities."}</h2></div><span className="badge">CPU SIMULATOR</span></div>{!result?<div className="quantum-empty"><Atom size={94} strokeWidth={.65}/><h3>Start with an entangled pair.</h3><p>Run the Bell circuit to see correlated 00 and 11 outcomes. This computes a statevector on your device.</p></div>:<>
        <div className="quantum-result-meta" role="status">{result.shots.toLocaleString()} sampled shots · {result.noise?`${result.noise*100}% readout flips`:"Ideal measurement"} · {result.probabilities.length} basis states</div>
        <div className="quantum-histogram">{result.probabilities.map((p,i)=>({p,i,count:result.counts[i]})).filter(v=>v.p>1e-9||v.count>0).map(({p,i,count})=><div className="quantum-hist-row" key={i}><code>|{i.toString(2).padStart(result.circuit.qubits,"0")}⟩</code><span className="quantum-bar"><i style={{width:`${p*100}%`}}/><b style={{width:`${count/result.shots*100}%`}}/></span><small>{(p*100).toFixed(1)}% · {count}</small></div>)}</div><p className="muted">Gold: ideal probability. Blue: sampled frequency. Counts vary between runs.</p>
        <div className="quantum-bloch">{result.bloch.map((b,q)=><div key={q}><svg viewBox="0 0 140 140" role="img" aria-label={`Qubit ${q} Bloch vector x ${b.x.toFixed(2)}, y ${b.y.toFixed(2)}, z ${b.z.toFixed(2)}`}><circle cx="70" cy="70" r="48"/><ellipse cx="70" cy="70" rx="48" ry="17"/><path d="M70 15V125 M15 70H125 M35 105L105 35"/><line x1="70" y1="70" x2={70+42*b.x+22*b.y} y2={70-42*b.z-22*b.y} className="quantum-vector"/><circle cx={70+42*b.x+22*b.y} cy={70-42*b.z-22*b.y} r="4" className="quantum-tip"/><text x="75" y="18">z</text><text x="122" y="65">x</text><text x="105" y="30">y</text></svg><strong>q{q}</strong><small>Purity {b.purity.toFixed(2)}</small></div>)}</div><p className="muted">Reduced single-qubit states before readout errors. A vector at the center is maximally mixed; entangled Bell qubits each have purity 0.50.</p>
        <button className="button secondary" onClick={()=>download("simulation-result.json",JSON.stringify({schema:"exaflop.quantum.result.v1",provider:"QuantumPad local simulator",backend:"browser-statevector",jobId:crypto.randomUUID(),status:"COMPLETED",observedAt:new Date().toISOString(),qubits:result.circuit.qubits,circuit:result.circuit,readoutError:result.noise,counts:Object.fromEntries(result.counts.map((v,i)=>[i.toString(2).padStart(result.circuit.qubits,"0"),v]))},null,2))}><Download size={15}/>Download result</button>
      </>}</section></div>
      <section className="panel quantum-section"><div className="quantum-section-heading"><div><span className="eyebrow">03 / COMPARE EXECUTIONS</span><h2>Bring back a hardware result.</h2><p>Import a runner result to compare its counts with the ideal simulation of the same circuit. Imported files are user-supplied, not independently verified.</p></div><label className="button secondary quantum-upload"><Upload size={15}/>Import result<input type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0],"result");e.target.value="";}}/></label></div>{imported&&<><p>{imported.provider} · {imported.backend} · {imported.status} · {importedShots} shots</p><p className="muted">Job {imported.jobId} · {imported.observedAt}</p><h3>Total variation distance: {distance.toFixed(4)}</h3><p className="muted">0 means matching distributions; 1 means no overlap. Finite sampling and noise both affect this statistic.</p><div className="quantum-histogram">{reference.map((p,i)=>({p,key:i.toString(2).padStart(imported.qubits,"0")})).filter(v=>v.p>1e-9||imported.counts[v.key]).map(({p,key})=><div className="quantum-hist-row" key={key}><code>{key}</code><span className="quantum-bar"><i style={{width:`${p*100}%`}}/><b style={{width:`${(imported.counts[key]??0)/importedShots*100}%`}}/></span><small>{imported.counts[key]??0} counts</small></div>)}</div></>}</section>
    </>}
    {tab==="devices"&&<>
      <section className="panel quantum-section"><span className="eyebrow">BRING YOUR OWN PROVIDER</span><h2>Real devices. Your account.</h2><p>Provider discovery and submissions run through the downloadable Python runner on your machine. QuantumPad does not store quantum credentials or submit paid quantum jobs from this page.</p><div className="quantum-actions"><a className="button primary" href="/downloads/exaflop-quantum.py" download><Download size={15}/>Download provider runner</a><a className="button secondary" href="/downloads/quantum-guide.md" download>Setup & commands</a><a className="button secondary" href="/downloads/quantum-requirements.txt" download>Tested SDK versions</a><button className="button secondary" onClick={request}>Export current circuit</button></div><p className="muted">Use Python 3.12. IBM: QISKIT_IBM_TOKEN and QISKIT_IBM_INSTANCE in your local environment. AWS: your standard AWS profile. No credentials go in downloaded JSON.</p><pre>python -m pip install qiskit qiskit-aer qiskit-ibm-runtime amazon-braket-sdk</pre></section>
      <div className="quantum-grid">{providers.map(p=><section className="panel quantum-section" key={p.name}><div className="quantum-section-heading"><h2>{p.name}</h2><Atom size={25}/></div><span className="badge">{p.kind} · EXTERNAL ACCOUNT</span><p>{p.description}</p><pre>{p.command}</pre><div className="quantum-actions"><a className="button secondary" href={p.url} target="_blank" rel="noreferrer">Provider console <ArrowUpRight size={14}/></a><a href={p.docs} target="_blank" rel="noreferrer">Official documentation ↗</a></div></section>)}</div>
      <section className="panel quantum-section"><div className="quantum-section-heading"><div><h2>Your device catalog</h2><p>Import devices.json from the runner. Queue and availability are dated snapshots; refresh in your provider account before submitting.</p></div><label className="button secondary quantum-upload"><Upload size={15}/>Import devices<input type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0],"devices");e.target.value="";}}/></label></div>{!devices.length?<p className="quantum-empty">No device snapshot loaded. Discover with IBM or AWS above. We do not invent live QPU capacity, prices, or physical locations.</p>:<><p className="muted">User-imported snapshot · {deviceDate}</p><div className="quantum-device-table"><table><thead><tr><th>Device</th><th>Provider</th><th>Qubits</th><th>Status / queue</th><th>Operations</th></tr></thead><tbody>{devices.map((d,i)=><tr key={i}><td>{d.name}</td><td>{d.provider}</td><td>{d.qubits??"Not reported"}</td><td>{d.status}<small>{d.queue}</small></td><td>{d.gates}</td></tr>)}</tbody></table></div></>}</section>
      <section className="panel quantum-section"><h2>Submit, track, retrieve.</h2><p>Replace BACKEND_NAME with a device from discovery. Submission asks for an explicit terminal confirmation because provider usage can cost money. Review pricing and quotas at the provider first.</p><pre>{'python exaflop-quantum.py run --provider ibm --backend BACKEND_NAME --request quantum-request.json\npython exaflop-quantum.py status --receipt quantum-job.json\npython exaflop-quantum.py result --receipt quantum-job.json\npython exaflop-quantum.py cancel --receipt quantum-job.json'}</pre><p className="muted">AWS uses --provider braket --backend DEVICE_ARN. Import quantum-result.json into Circuit lab. External quantum jobs are tracked by the runner/provider, separately from QuantumPad GPU jobs.</p><a href="https://aws.amazon.com/braket/pricing/" target="_blank" rel="noreferrer">Braket pricing ↗</a> · <a href="https://quantum.cloud.ibm.com/docs/en/guides/plans-overview" target="_blank" rel="noreferrer">IBM plans ↗</a></section>
    </>}
    {tab==="simulation"&&<>
      <div className="quantum-grid"><section className="panel quantum-section"><Cpu size={32} strokeWidth={1.2}/><h2>Classical GPUs. Quantum circuits.</h2><p>Use Qiskit Aer on CUDA hardware to simulate your exported circuit. GPU simulation is classical computation, not access to a QPU.</p><div className="quantum-actions"><Link className="button primary" href="/build?template=quantum&gpu=A100">Configure a simulation GPU <ArrowUpRight size={15}/></Link><a className="button secondary" href="/downloads/exaflop-quantum.py" download>Download runner</a><button className="button secondary" onClick={request}>Export circuit</button></div><pre>{'python -m pip install qiskit qiskit-aer-gpu\npython exaflop-quantum.py run --provider gpu --request quantum-request.json'}</pre><p className="muted">Requires a supported Linux NVIDIA CUDA environment. The runner checks GPU availability and fails explicitly if unavailable. This starter runner is bounded to 8 qubits; extend it locally for larger research workloads.</p><a href="/downloads/quantum-guide.md" download>Simulation setup guide</a></section>
      <section className="panel quantum-section"><span className="eyebrow">MEMORY PLANNER</span><h2>Know the exponential cost.</h2><label>Planning qubits: {memoryQubits}<input aria-label="Planning qubits" type="range" min="8" max="40" value={memoryQubits} onChange={e=>setMemoryQubits(+e.target.value)}/></label><div className="quantum-memory">{(16*2**memoryQubits/2**30).toLocaleString(undefined,{maximumFractionDigits:3})}<small>GiB raw statevector</small></div><p>Complex128 statevector: 16 × 2ⁿ bytes. This excludes work buffers, framework overhead, communication, and circuit storage. It is a lower bound, not a hardware-fit guarantee.</p><p className="muted">Density-matrix simulation scales as 16 × 4ⁿ bytes. Tensor-network costs depend on circuit structure and cannot be inferred from qubit count alone.</p></section></div>
    </>}
    {tab==="hybrid"&&<>
      <div className="quantum-grid"><section className="panel quantum-section"><Network size={30} strokeWidth={1.2}/><h2>Optimize a quantum experiment.</h2><p>A classical parameter search repeatedly evaluates a quantum circuit. These small examples run entirely in the local simulator, with exact expectations.</p><label>Experiment<select value={algorithm} onChange={e=>{setAlgorithm(e.target.value as "qaoa"|"vqe");setHybrid(null);}}><option value="qaoa">QAOA · two-node MaxCut</option><option value="vqe">VQE · one-qubit Hamiltonian</option></select></label><p>{algorithm==="qaoa"?"Maximize the cut probability for one edge. Search a 17 × 17 grid of gamma and beta for a depth-1 circuit. The optimum cut value is 1.":"Minimize ⟨Z + 0.5X⟩ with an RY ansatz across 65 angles. The exact ground-state energy is −√1.25 ≈ −1.118034."}</p><button className="button primary" onClick={()=>setHybrid(hybridSweep(algorithm))}><Play size={15}/>Run parameter search</button><p className="muted">Educational baselines, not evidence of quantum advantage. No cloud charges.</p></section>
      <section className="panel quantum-section"><span className="eyebrow">OPTIMIZATION TRACE</span><h2>{hybrid?`Best ${hybrid.kind==="vqe"?"energy":"expected cut"}: ${hybrid.best.toFixed(6)}`:"Watch the search converge."}</h2>{hybrid?<><svg className="quantum-trace" viewBox="0 0 600 220" role="img" aria-label={`Best objective across ${hybrid.history.length} evaluations`}><path d="M20 10V200H590"/><polyline points={hybrid.history.map((h,i)=>`${20+i/(hybrid.history.length-1)*570},${190-(hybrid.kind==="vqe"?(h.best+1.2)/2.4:h.best)*170}`).join(" ")}/></svg><p>{hybrid.history.length} evaluations · Parameters: {hybrid.parameters.map(p=>p.toFixed(4)).join(", ")} radians</p><div className="quantum-actions"><button className="button secondary" onClick={()=>{edit(hybrid.circuit);setTab("lab");}}>Open winning circuit</button><button className="button secondary" onClick={()=>download("hybrid-trace.json",JSON.stringify(hybrid,null,2))}>Export trace</button></div></>:<div className="quantum-empty"><Network size={75} strokeWidth={.7}/><p>Run an experiment to see computed objective values.</p></div>}</section></div>
      <section className="panel quantum-section"><h2>Move the loop to Amazon Braket.</h2><p>Download the bounded VQE workflow to run through Braket Hybrid Jobs with your AWS account. It uses a classical job instance plus a selected simulator or QPU; both may incur charges. Maximum 9 evaluations × 2 measurement circuits × 128 shots = 2,304 shots.</p><div className="quantum-actions"><a className="button primary" href="/downloads/exaflop-hybrid.py" download><Download size={15}/>Download hybrid runner</a><a href="https://docs.aws.amazon.com/braket/latest/developerguide/braket-hybrid-job-decorator.html" target="_blank" rel="noreferrer">Braket Hybrid Jobs guide ↗</a></div><pre>{'python exaflop-hybrid.py --device DEVICE_ARN\npython exaflop-hybrid.py --status JOB_ARN\npython exaflop-hybrid.py --result JOB_ARN\npython exaflop-hybrid.py --cancel JOB_ARN'}</pre><p className="muted">Python 3.12, amazon-braket-sdk and a configured AWS profile required. Execution asks for terminal confirmation. Cancel outstanding quantum tasks in the provider console if a hybrid job is interrupted.</p></section>
    </>}
    <p className="quantum-footnote">QuantumPad quantum tools use ordinary classical simulation unless a provider job explicitly identifies a QPU. Provider availability, billing and results remain authoritative at the provider.</p>
  </div>;
}
