"use client";
import Link from "next/link";
import Image from "next/image";
import {QuantumLaunchStack} from "./quantum-launch-stack";
import {useLaunchDirectory,LaunchRefresh} from "./launch-directory";
import {Atom,ArrowUpRight,Code2,Workflow,Activity,Cpu,ArrowRight,FileCheck2} from "lucide-react";

import {genesisArt} from "@/lib/genesis-art";


export function QuantumHomeHero(){return <>
 <nav className="quantum-home-nav" aria-label="QuantumPad primary navigation"><Link href="/" className="quantum-home-brand"><Image src="/quantumpad-logo.png" width={32} height={32} alt=""/>quantumpad</Link><div><Link href="/launchpad">Launchpad</Link><Link href="/quantum">Quantum lab</Link><Link href="/playground">Live playground</Link><Link href="/markets">Compute workspace</Link><Link href="/compute-index">Earth &amp; compute index</Link></div><details className="home-mobile-menu" onKeyDown={e=>{if(e.key==="Escape"){e.currentTarget.open=false;e.currentTarget.querySelector("summary")?.focus();}}}><summary>Menu <span aria-hidden="true">☰</span></summary><div onClick={e=>{if((e.target as HTMLElement).closest("a"))e.currentTarget.closest("details")?.removeAttribute("open");}}><Link href="/launchpad">Launchpad</Link><Link href="/quantum">Quantum lab</Link><Link href="/playground">Live playground</Link><Link href="/markets">Compute workspace</Link><Link href="/compute-index">Earth &amp; compute index</Link><Link className="quantum-home-launch" href="/launchpad?create=hardware">Create a launch <ArrowUpRight size={15}/></Link></div></details><Link className="quantum-home-launch" href="/launchpad?create=hardware">Create a launch <ArrowUpRight size={15}/></Link></nav>
 <header className="quantum-home-hero"><span className="eyebrow">QUANTUMPAD / QUANTUM COMPUTING LAUNCHPAD</span><h1>Quantum computing.<br/>Your token’s origin.</h1><p>Launch a token around your quantum computing project—from hardware experiments and classical simulations to software releases and hybrid applications.</p><div className="quantum-home-actions"><Link className="quantum-home-launch" href="/launchpad?create=hardware">Create a launch <ArrowUpRight size={17}/></Link><Link href="/launchpad">Explore launches <ArrowRight size={16}/></Link></div><div className="quantum-home-proof"><Atom size={18}/><span>Experiment → Genesis record → Token market</span></div><p className="quantum-home-disclosure">Robinhood Chain · Wallet-signed launches<br/>Quantum evidence is creator-submitted and publicly inspectable.</p></header>
 <a className="quantum-home-scroll" href="#latest-launches">Discover latest launches ↓</a>
 </>;}

export function QuantumHomeSections(){
 const directory=useLaunchDirectory();
 const {loading,error}=directory;const records=directory.records.slice(0,6);
 return <div className="quantum-home-sections">
 <section id="latest-launches" className="quantum-home-directory"><div className="quantum-home-section-heading"><div><span className="eyebrow">CREATED ON QUANTUMPAD</span><h2>Latest launches.</h2></div><Link href="/launchpad">View all projects <ArrowUpRight size={16}/></Link></div><LaunchRefresh directory={directory}/>{loading?<p role="status">Loading published projects…</p>:error&&!records.length?<p role="status">{error} <Link href="/launchpad">Open launchpad ↗</Link></p>:records.length?<div className="quantum-home-records">{records.map(r=><Link key={r.id} href={`/launchpad/${r.id}`}><img src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(genesisArt(r.digest))}`} width={100} height={100} alt={`${r.manifest.project.name} genesis artwork`}/><div><span className="eyebrow">{r.deployment?"TOKEN DEPLOYED":"GENESIS PUBLISHED"}</span><h3>{r.manifest.project.name}</h3><p>{r.manifest.project.description.slice(0,130)}</p><span className="text-link">Explore ${r.manifest.project.symbol} ↗</span></div></Link>)}</div>:<div className="quantum-home-empty"><Atom size={36} strokeWidth={1.2}/><div><h3>The next genesis could be yours.</h3><p>No projects have been published yet. Start with an experiment or a software release.</p></div><Link className="button primary" href="/launchpad?create=hardware">Create the first launch ↗</Link></div>}</section>
 <QuantumLaunchStack/>
 <section id="genesis-paths" className="quantum-home-paths"><div className="quantum-home-section-heading"><div><span className="eyebrow">START WITH SOMETHING REAL</span><h2>What will your genesis be?</h2></div><Link href="/launchpad">All seven launch paths <ArrowUpRight size={16}/></Link></div><div className="quantum-home-path-grid"><Link className="quantum-home-path featured" href="/launchpad?create=hardware"><Atom size={34} strokeWidth={1.3}/><span className="eyebrow">01 / HARDWARE GENESIS</span><h3>From a circuit<br/>to a creation.</h3><p>Attach a quantum hardware result, publish the circuit and job reference, and derive your token’s artwork from its genesis record.</p><span className="text-link">Start a hardware launch <ArrowUpRight size={16}/></span></Link><div className="quantum-home-path-stack"><Link className="quantum-home-path" href="/launchpad?create=software"><Code2 size={26}/><div><span className="eyebrow">02 / SOFTWARE LAUNCH</span><h3>Ship the software. Launch the token.</h3><p>Give your project a public origin with a pinned release, source and working demo.</p><span className="text-link">Start a software launch ↗</span></div></Link><Link className="quantum-home-path" href="/launchpad?create=hybrid"><Workflow size={26}/><div><span className="eyebrow">03 / HYBRID ENGINE</span><h3>Bring both worlds together.</h3><p>Connect classical compute and a quantum backend in a versioned application.</p><span className="text-link">Start a hybrid launch ↗</span></div></Link></div></div></section>
 <section className="quantum-home-lifecycle" aria-label="Launch lifecycle"><div><FileCheck2 size={24}/><strong>Commit the origin</strong><p>Publish evidence, project details and deterministic artwork in an immutable genesis manifest.</p></div><ArrowRight aria-hidden="true"/><div><Activity size={24}/><strong>Open the market</strong><p>Choose an integrated ETH curve, trade in the app and graduate to locked Uniswap v4 liquidity.</p></div><Link href="/launchpad">Explore the launchpad <ArrowUpRight size={17}/></Link></section>

 <section id="compute-tools" className="quantum-home-support"><div><span className="eyebrow">THE TOOLS BEHIND YOUR LAUNCH</span><h2>Build the work<br/>behind the token.</h2><p>QuantumPad’s compute workspace supports the project you’re launching. Explore hardware, test ideas and plan the resources your application needs.</p></div><nav aria-label="Supporting compute tools"><Link href="/quantum"><Atom size={23}/><div><strong>Quantum lab</strong><span>Build circuits, simulate and prepare provider workflows.</span></div><ArrowUpRight size={17}/></Link><Link href="/playground"><Activity size={23}/><div><strong>Live playground</strong><span>Run local computation and inspect measured output.</span></div><ArrowUpRight size={17}/></Link><Link href="/markets"><Cpu size={23}/><div><strong>Compute workspace</strong><span>Compare GPU offers and configure your machine.</span></div><ArrowUpRight size={17}/></Link><Link href="/compute-index"><Activity size={23}/><div><strong>Earth & compute index</strong><span>Explore regional offers and observed price history.</span></div><ArrowUpRight size={17}/></Link></nav></section>
 </div>;
}
